code/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Http\Request;

Route::name("index.")->middleware('spider')->group(function() {
    Route::get('/','Home\IndexController@index')->name("home");
    Route::get('/product','Home\ProductController@index')->name("product.list");
    Route::get('/productshow/{product}','Home\ProductController@show')->name("product.show");
    Route::get('/news','Home\NewsController@index')->name("news.list");
    Route::get('/news/{news}','Home\NewsController@show')->name("news.show");
    Route::get('/cases','Home\CasesController@index')->name("cases.list");
    Route::get('/abount','Home\PageController@index')->name("page.index");
});
//后台路由
Route::prefix("admin")->name("admin.")->middleware('auth')->group(function(){
    Route::get("/","Admin\IndexController@index")->name("home");
    Route::get("/index","Admin\IndexController@index")->name("home");
    Route::group(['prefix'=>'config'],function(){
        Route::get("/site","Admin\ConfigController@siteconfig")->name("config.siteconfig");
        Route::get("/information","Admin\ConfigController@information")->name("config.information");
        Route::get("/baidu","Admin\ConfigController@baidu")->name("config.baidu");
        Route::post("/store","Admin\ConfigController@store")->name("config.store");
    });
    //新闻
    Route::resource("/news","Admin\NewsController")->except(['destroy','create']);
    Route::get('admin/news/add','Admin\NewsController@create')->name('news.create');
    Route::get('admin/news/{news}/del','Admin\NewsController@destroy')->name("news.delete");
    Route::get('admin/news/baidusend/{news}','Admin\NewsController@baidusend')->name("news.baidusend");

    //产品分类
    Route::group(['prefix'=>'category'],function(){
        Route::get("/","Admin\CategoryController@index")->name("category.list");
        Route::match(['get','post'],"/create","Admin\CategoryController@create")->name("category.create");
        Route::match(['get','post'],"/edit/{category}","Admin\CategoryController@edit")->name("category.edit");
        Route::get("/delete/{cate}","Admin\CategoryController@destory")->name("category.delete");
    });
    Route::resource("/product","Admin\ProductController");
    Route::resource("/cases","Admin\CaseController");
    Route::get("/page/createzx","Admin\PageController@createzx")->name('page.createzx');
    Route::get("/page/licheng","Admin\PageController@licheng")->name('page.licheng');
    Route::get("/page/createlc","Admin\PageController@createlc")->name('page.createlc');
    Route::get("/page/editlc/{page}","Admin\PageController@editlc")->name('page.editlc');
    Route::get("/page/jianjie","Admin\PageController@create")->name('page.create');
    Route::resource("/page","Admin\PageController")->except("create");
    Route::resource("/banner","Admin\BannerController");
    Route::post('/banneritem/setsort',"Admin\BanneritemController@setsort")->name('banneritem.setsort');
    Route::resource("/banneritem","Admin\BanneritemController");
    Route::resource("/friend","Admin\FriendController");
    //登录
    Route::get('/logout','Admin\LoginController@logout')->name('login.logout');
    //图片上传
    Route::post('upload','Admin\IndexController@imgupload')->name("upload");
});
Route::get('/admin/login','Admin\LoginController@login')->name('admin.login.login');
Route::post('/admin/dologin','Admin\LoginController@dologin')->name('admin.login.dologin');

code/app/News.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class News extends Model
{
    //
}

code/app/Http/Controllers/Admin/NewsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\StoreNewsPost;
use App\Libs\Baidu;
use App\News;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;

class NewsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $NewsModel = new News;
        $list = $NewsModel::orderBy('created_at','Desc')->orderBy('id','Desc')->paginate(10);
        return view("admin.news.index")->with('list',$list);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("admin.news.create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreNewsPost $request)
    {
        //
        $NewsModel = new News;
        $NewsModel->title = $request->title;
        $NewsModel->keyword = $request->keyword;
        $NewsModel->desc = $request->desc;
        $NewsModel->remark = $request->remark;
        $NewsModel->views = $request->views;
        $NewsModel->content = $request->contents;
        if($request->file("file")){
            $NewsModel->pic = $request->file('file')->store('news');
        }
        checkreturn($NewsModel->save(),"新增");
        return redirect(route('admin.news.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\News  $news
     * @return \Illuminate\Http\Response
     */
    public function show(News $news)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\News  $news
     * @return \Illuminate\Http\Response
     */
    public function edit(News $news)
    {
        //
        return view('admin.news.edit')->with('news',$news);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\News  $news
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, News $news)
    {
        //
        $data =[
            'title'=>$request->title,
            'keyword'=>$request->keyword,
            'desc'=>$request->desc,
            'remark'=>$request->remark,
            'views'=>$request->views,
            'content'=>$request->contents,
        ];
        if($request->file("file")){
            $data['pic'] = $request->file('file')->store('news');
            //删除旧图片
            Storage::delete($news->pic);
        }
        $NewsModel = new News;
        $result = $NewsModel::where('id','=',$news->id)->update($data);
        checkreturn($result>0,"修改");
        return redirect(route('admin.news.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\News  $newsN
     * @return \Illuminate\Http\Response
     */
    public function destroy(News $news)
    {
        //
//        $result = (new News)::destroy($news->id);
        $result = $news->delete();
        Storage::delete($news->pic);
        checkreturn($result,"删除");
        return redirect(route('admin.news.index'));
    }
    //百度推送
    public function baidusend(News $news){
        //
        $url = route('index.news.show',['news'=>$news->id]);
//        $url = "http://www.yfketang.cn/course-show/9.html";
        $result = Baidu::getInstance()->baidusend([$url]);
        checkreturn($result,"推送");
        return redirect(route('admin.news.index'));
    }
}

code/app/Http/Controllers/Home/NewsController.php
<?php

namespace App\Http\Controllers\Home;

use App\Banner;
use App\Http\Controllers\Controller;
use App\News;
use Illuminate\Http\Request;

class NewsController extends Controller
{
    protected $banner;

    public function __construct()
    {
        //获取banner
        $banner = Banner::where('entitle','=','news')->first();
        $this->banner  = $banner->banneritem[0];
    }
    // 列表
    public function index(){
        $list = News::OrderBy('created_at','Desc')->OrderBy('id','Desc')->paginate(10);
        return view('home.news.index')->with('list',$list)->with('banners',$this->banner);
    }

    //详情
    public function show(News $news){
        News::where('id',$news->id)->increment('views',1);
        return view('home.news.show')->with('news',$news)->with('banners',$this->banner);
    }
}

code/resources/views/admin/news/create.blade.php
@extends('admin.default');
@section("title","新闻管理")
@section("content")
    <div class="page-header">
        <h3 class="page-title">
            新闻管理
        </h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">新闻管理</a></li>
                <li class="breadcrumb-item active" aria-current="page">添加新闻</li>
            </ol>
        </nav>
    </div>
    <div class="row">
        <div class="col-md-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    @if ($errors->any())
                        @foreach ($errors->all() as $error)
                        <div class="alert alert-danger">
                            {{ $error }}
                        </div>
                        @endforeach
                    @endif
                    <form class="forms-sample" action="{{route('admin.news.store')}}" method="post" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group">
                            <label for="title">新闻标题</label>
                            <input type="text" name="title" class="form-control" id="title" placeholder="请输入标题">
                        </div>

                        <div class="form-group">
                            <label for="keyword">关键字</label>
                            <input type="text" name="keyword" class="form-control" id="keyword" placeholder="请输入关键字">
                        </div>
                        <div class="form-group">
                            <label for="desc">描述</label>
                            <textarea class="form-control" name="desc" id="desc" rows="4" placeholder="请输入描述"></textarea>
                        </div>
                        <div class="form-group">
                            <label for="remark">摘要</label>
                            <textarea class="form-control" name="remark" id="remark" rows="4" placeholder="请输入摘要"></textarea>
                        </div>
                        <div class="form-group">
                            <label for="views">浏览次数</label>
                            <input type="text" name="views" value="0" class="form-control" id="views" placeholder="请输入浏览次数">
                        </div>
                        <div class="form-group">
                            <label>图片上传</label>
                            <input type="file" name="file" class="file-upload-default">
                            <div class="input-group col-xs-12">
                                <input type="text" class="form-control file-upload-info" disabled="" placeholder="图片上传">
                                <span class="input-group-append">
                          <button class="file-upload-browse btn btn-gradient-primary" type="button">选择图片</button>
                        </span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="contents">新闻内容</label>
                            {{--<textarea class="form-control" name="contents" id="contents" rows="4" praceholder="请输入新闻内容"></textarea>--}}
                            <script id="contents" name="contents" type="text/plain"></script>
                        </div>
                        <button type="submit" class="btn btn-gradient-primary mr-2">保存</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript" id="ne1" charset="utf-8" src="{{ asset(__ADMIN__) }}/neditor/neditor.config.js?v={{time()}}"></script>
    <script type="text/javascript" id="ne2"  charset="utf-8" src="{{ asset(__ADMIN__) }}/neditor/neditor.all.min.js?v={{time()}}"> </script>
    <script type="text/javascript" id="ne3" charset="utf-8" src="{{ asset(__ADMIN__) }}/neditor/neditor.service.js?v={{time()}}"></script>
    <script>
        setTimeout(function(){
            var ue = UE.getEditor('contents', {
                autoHeight: false,
                initialFrameHeight:300
            });
        },1000)
    </script>
@endsection

code/resources/views/admin/news/edit.blade.php
@extends('admin.default');
@section("title","新闻管理")
@section("content")
    <div class="page-header">
        <h3 class="page-title">
            新闻管理
        </h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">新闻管理</a></li>
                <li class="breadcrumb-item active" aria-current="page">编辑新闻</li>
            </ol>
        </nav>
    </div>
    <div class="row">
        <div class="col-md-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    @if ($errors->any())
                        @foreach ($errors->all() as $error)
                        <div class="alert alert-danger">
                            {{ $error }}
                        </div>
                        @endforeach
                    @endif
                    <form class="forms-sample" action="{{route('admin.news.update',['news'=>$news->id])}}" method="post" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                            <label for="title">新闻标题</label>
                            <input type="text" name="title" value="{{$news->title}}" class="form-control" id="title" placeholder="请输入标题">
                        </div>

                        <div class="form-group">
                            <label for="keyword">关键字</label>
                            <input type="text" name="keyword" value="{{$news->keyword}}" class="form-control" id="keyword" placeholder="请输入关键字">
                        </div>
                        <div class="form-group">
                            <label for="desc">描述</label>
                            <textarea class="form-control" name="desc" id="desc" rows="4" placeholder="请输入描述">{{$news->desc}}</textarea>
                        </div>
                        <div class="form-group">
                            <label for="remark">摘要</label>
                            <textarea class="form-control" name="remark" id="remark" rows="4" placeholder="请输入摘要">{{$news->remark}}</textarea>
                        </div>
                        <div class="form-group">
                            <label for="views">浏览次数</label>
                            <input type="text" name="views" value="{{$news->views}}" class="form-control" id="views" placeholder="请输入浏览次数">
                        </div>
                        <div class="form-group">
                            <label>图片上传</label>
                            <input type="file" name="file" class="file-upload-default">
                            <div class="input-group col-xs-12">
                                <input type="text" value="{{$news->pic}}" class="form-control file-upload-info" disabled="" placeholder="图片上传">
                                <span class="input-group-append">
                          <button class="file-upload-browse btn btn-gradient-primary" type="button">选择图片</button>
                        </span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="contents">新闻内容</label>
                            {{--<textarea class="form-control" name="contents" id="contents" rows="4" praceholder="请输入新闻内容"></textarea>--}}
                            <script id="contents" name="contents" type="text/plain">{!! $news->content !!}</script>
                        </div>
                        <button type="submit" class="btn btn-gradient-primary mr-2">保存</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript" id="ne1" charset="utf-8" src="{{ asset(__ADMIN__) }}/neditor/neditor.config.js?v={{time()}}"></script>
    <script type="text/javascript" id="ne2"  charset="utf-8" src="{{ asset(__ADMIN__) }}/neditor/neditor.all.min.js?v={{time()}}"> </script>
    <script type="text/javascript" id="ne3" charset="utf-8" src="{{ asset(__ADMIN__) }}/neditor/neditor.service.js?v={{time()}}"></script>
    <script>
        setTimeout(function(){
            var ue = UE.getEditor('contents', {
                autoHeight: false,
                initialFrameHeight:300
            });
        },1000)
    </script>
@endsection

code/resources/views/admin/news/index.blade.php
@extends('admin.default');
@section("title","新闻管理")
@section("content")
    <div class="page-header">
        <h3 class="page-title">
            新闻管理
        </h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">新闻管理</a></li>
                <li class="breadcrumb-item active" aria-current="page">新闻列表</li>
            </ol>
        </nav>
    </div>
    <div class="row">
        <div class="col-md-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    @if(session()->has("data"))
                        <div class="alert alert-{{session("data")['class']}}">
                            {{ session('data')['msg'] }}
                        </div>
                    @endif

                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <th class="text-center">ID</th>
                                <th>标题</th>
                                <th class="text-center">浏览次数</th>
                                <th class="text-center">发布时间</th>
                                <th class="text-center" style="width:280px;">操作</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($list as $item)
                            <tr>
                                <td class="text-center">{{ $item->id }}</td>
                                <td>{{ $item->title }}</td>
                                <td class="text-center">{{ $item->views }}</td>
                                <td class="text-center">{{ $item->created_at }}</td>
                                <td class="text-center">
                                    <a class="btn btn-success btn-xs" href="{{ route('admin.news.baidusend',['news'=>$item->id]) }}" role="button">百度推送</a>
                                    <a class="btn btn-success btn-xs" href="{{ route('admin.news.edit',['news'=>$item->id]) }}" role="button">编辑</a>
                                    <a class="btn btn-danger btn-xs" href="{{route('admin.news.delete',['news'=>$item->id])}}" role="button">删除</a>
                                </td>
                            </tr>
                                @endforeach
                            </tbody>
                        </table>
                        <div style="padding:10px 0;">
                            {{ $list->links() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection