code/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Http\Request;

Route::name("index.")->middleware('spider')->group(function() {
    Route::get('/','Home\IndexController@index')->name("home");
    Route::get('/product','Home\ProductController@index')->name("product.list");
    Route::get('/productshow/{product}','Home\ProductController@show')->name("product.show");
    Route::get('/news','Home\NewsController@index')->name("news.list");
    Route::get('/news/{news}','Home\NewsController@show')->name("news.show");
    Route::get('/cases','Home\CasesController@index')->name("cases.list");
    Route::get('/abount','Home\PageController@index')->name("page.index");
});
//后台路由
Route::prefix("admin")->name("admin.")->middleware('auth')->group(function(){
    Route::get("/","Admin\IndexController@index")->name("home");
    Route::get("/index","Admin\IndexController@index")->name("home");
    Route::group(['prefix'=>'config'],function(){
        Route::get("/site","Admin\ConfigController@siteconfig")->name("config.siteconfig");
        Route::get("/information","Admin\ConfigController@information")->name("config.information");
        Route::get("/baidu","Admin\ConfigController@baidu")->name("config.baidu");
        Route::post("/store","Admin\ConfigController@store")->name("config.store");
    });
    //新闻
    Route::resource("/news","Admin\NewsController")->except(['destroy','create']);
    Route::get('admin/news/add','Admin\NewsController@create')->name('news.create');
    Route::get('admin/news/{news}/del','Admin\NewsController@destroy')->name("news.delete");
    Route::get('admin/news/baidusend/{news}','Admin\NewsController@baidusend')->name("news.baidusend");

    //产品分类
    Route::group(['prefix'=>'category'],function(){
        Route::get("/","Admin\CategoryController@index")->name("category.list");
        Route::match(['get','post'],"/create","Admin\CategoryController@create")->name("category.create");
        Route::match(['get','post'],"/edit/{category}","Admin\CategoryController@edit")->name("category.edit");
        Route::get("/delete/{cate}","Admin\CategoryController@destory")->name("category.delete");
    });
    Route::resource("/product","Admin\ProductController");
    Route::resource("/cases","Admin\CaseController");
    Route::get("/page/createzx","Admin\PageController@createzx")->name('page.createzx');
    Route::get("/page/licheng","Admin\PageController@licheng")->name('page.licheng');
    Route::get("/page/createlc","Admin\PageController@createlc")->name('page.createlc');
    Route::get("/page/editlc/{page}","Admin\PageController@editlc")->name('page.editlc');
    Route::get("/page/jianjie","Admin\PageController@create")->name('page.create');
    Route::resource("/page","Admin\PageController")->except("create");
    Route::resource("/banner","Admin\BannerController");
    Route::post('/banneritem/setsort',"Admin\BanneritemController@setsort")->name('banneritem.setsort');
    Route::resource("/banneritem","Admin\BanneritemController");
    Route::resource("/friend","Admin\FriendController");
    //登录
    Route::get('/logout','Admin\LoginController@logout')->name('login.logout');
    //图片上传
    Route::post('upload','Admin\IndexController@imgupload')->name("upload");
});
Route::get('/admin/login','Admin\LoginController@login')->name('admin.login.login');
Route::post('/admin/dologin','Admin\LoginController@dologin')->name('admin.login.dologin');

code/resources/views/admin/page/create.blade.php
@extends('admin.default');
@section("title","单页管理")
@section("content")
    <div class="page-header">
        <h3 class="page-title">
            单页管理
        </h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">单页管理</a></li>
                <li class="breadcrumb-item active" aria-current="page">公司简介</li>
            </ol>
        </nav>
    </div>
    <div class="row">
        <div class="col-md-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    @if ($errors->any())
                        @foreach ($errors->all() as $error)
                        <div class="alert alert-danger">
                            {{ $error }}
                        </div>
                        @endforeach
                    @endif
                    <form class="forms-sample" action="{{route('admin.page.store')}}" method="post" enctype="multipart/form-data">
                        @csrf
                        <input type="hidden" name="type" value="1">
                        <div class="form-group">
                            <label for="title">标题</label>
                            <input type="text" value="{{isset($jianjie->title)?$jianjie->title:''}}" name="title" class="form-control" id="title" placeholder="请输入标题">
                        </div>
                        <div class="form-group">
                            <label for="remark">摘要</label>
                            <textarea class="form-control" name="remark" id="remark" rows="4" placeholder="请输入摘要">{{isset($jianjie->remark)?$jianjie->remark:''}}</textarea>
                        </div>
                        <div class="form-group">
                            <label>图片上传</label>
                            <input type="file" name="file" class="file-upload-default">
                            <div class="input-group col-xs-12">
                                <input type="text" value="{{isset($jianjie->pic)?$jianjie->pic:''}}" class="form-control file-upload-info" disabled="" placeholder="图片上传">
                                <span class="input-group-append">
                          <button class="file-upload-browse btn btn-gradient-primary" type="button">选择图片</button>
                        </span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="contents">详情</label>
                            {{--<textarea class="form-control" name="contents" id="contents" rows="4" praceholder="请输入新闻内容"></textarea>--}}
                            <script id="contents" name="contents" type="text/plain">{!! isset($jianjie->content)?$jianjie->content:''  !!}</script>
                        </div>
                        <button type="submit" class="btn btn-gradient-primary mr-2">保存</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript" id="ne1" charset="utf-8" src="{{ asset(__ADMIN__) }}/neditor/neditor.config.js?v={{time()}}"></script>
    <script type="text/javascript" id="ne2"  charset="utf-8" src="{{ asset(__ADMIN__) }}/neditor/neditor.all.min.js?v={{time()}}"> </script>
    <script type="text/javascript" id="ne3" charset="utf-8" src="{{ asset(__ADMIN__) }}/neditor/neditor.service.js?v={{time()}}"></script>
    <script>
        setTimeout(function(){
            var ue = UE.getEditor('contents', {
                autoHeight: false,
                initialFrameHeight:300
            });
        },1000)
    </script>
@endsection

code/resources/views/admin/page/createlc.blade.php
@extends('admin.default');
@section("title","发展历程")
@section("content")
    <div class="page-header">
        <h3 class="page-title">
            发展历程
        </h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">发展历程</a></li>
                <li class="breadcrumb-item active" aria-current="page">添加历程</li>
            </ol>
        </nav>
    </div>
    <div class="row">
        <div class="col-md-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    @if ($errors->any())
                        @foreach ($errors->all() as $error)
                        <div class="alert alert-danger">
                            {{ $error }}
                        </div>
                        @endforeach
                    @endif
                    <form class="forms-sample" action="{{route('admin.page.store')}}" method="post" enctype="multipart/form-data">
                        @csrf
                        <input type="hidden" name="type" value="3">
                        <div class="form-group">
                            <label for="title">时间</label>
                            <input type="text" name="title" class="form-control" id="title" placeholder="请输入时间">
                        </div>
                        <div class="form-group">
                            <label>图片上传</label>
                            <input type="file" name="file" class="file-upload-default">
                            <div class="input-group col-xs-12">
                                <input type="text" class="form-control file-upload-info" disabled="" placeholder="图片上传">
                                <span class="input-group-append">
                          <button class="file-upload-browse btn btn-gradient-primary" type="button">选择图片</button>
                        </span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="remark">历程</label>
                            <textarea class="form-control" name="remark" id="remark" rows="4" praceholder="请输入历程"></textarea>
                        </div>
                        <button type="submit" class="btn btn-gradient-primary mr-2">保存</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script>
        setTimeout(function(){
            var ue = UE.getEditor('contents', {
                autoHeight: false,
                initialFrameHeight:300
            });
        },1000)
    </script>
@endsection

code/resources/views/admin/page/createzx.blade.php
@extends('admin.default');
@section("title","招贤纳士")
@section("content")
    <div class="page-header">
        <h3 class="page-title">
            招贤纳士
        </h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">招贤纳士</a></li>
                <li class="breadcrumb-item active" aria-current="page">添加职位</li>
            </ol>
        </nav>
    </div>
    <div class="row">
        <div class="col-md-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    @if ($errors->any())
                        @foreach ($errors->all() as $error)
                        <div class="alert alert-danger">
                            {{ $error }}
                        </div>
                        @endforeach
                    @endif
                    <form class="forms-sample" action="{{route('admin.page.store')}}" method="post" enctype="multipart/form-data">
                        @csrf
                        <input type="hidden" name="type" value="2">
                        <div class="form-group">
                            <label for="title">标题</label>
                            <input type="text" name="title" class="form-control" id="title" placeholder="请输入标题">
                        </div>
                        <div class="form-group">
                            <label for="contents">职位描述</label>
                            {{--<textarea class="form-control" name="contents" id="contents" rows="4" praceholder="请输入新闻内容"></textarea>--}}
                            <script id="contents" name="contents" type="text/plain"></script>
                        </div>
                        <button type="submit" class="btn btn-gradient-primary mr-2">保存</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript" id="ne1" charset="utf-8" src="{{ asset(__ADMIN__) }}/neditor/neditor.config.js?v={{time()}}"></script>
    <script type="text/javascript" id="ne2"  charset="utf-8" src="{{ asset(__ADMIN__) }}/neditor/neditor.all.min.js?v={{time()}}"> </script>
    <script type="text/javascript" id="ne3" charset="utf-8" src="{{ asset(__ADMIN__) }}/neditor/neditor.service.js?v={{time()}}"></script>
    <script>
        setTimeout(function(){
            var ue = UE.getEditor('contents', {
                autoHeight: false,
                initialFrameHeight:300
            });
        },1000)
    </script>
@endsection

code/resources/views/admin/page/editlc.blade.php
@extends('admin.default');
@section("title","发展历程")
@section("content")
    <div class="page-header">
        <h3 class="page-title">
            发展历程
        </h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">发展历程</a></li>
                <li class="breadcrumb-item active" aria-current="page">添加历程</li>
            </ol>
        </nav>
    </div>
    <div class="row">
        <div class="col-md-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    @if ($errors->any())
                        @foreach ($errors->all() as $error)
                        <div class="alert alert-danger">
                            {{ $error }}
                        </div>
                        @endforeach
                    @endif
                    <form class="forms-sample" action="{{route('admin.page.update',['page'=>$page->id])}}" method="post" enctype="multipart/form-data">
                        @csrf
                        @method("PUT")
                        <input type="hidden" name="type" value="3">
                        <div class="form-group">
                            <label for="title">时间</label>
                            <input type="text" name="title" value="{{$page->title}}" class="form-control" id="title" placeholder="请输入时间">
                        </div>
                        <div class="form-group">
                            <label>图片上传</label>
                            <input type="file" name="file" class="file-upload-default">
                            <div class="input-group col-xs-12">
                                <input type="text" value="{{$page->pic}}" class="form-control file-upload-info" disabled="" placeholder="图片上传">
                                <span class="input-group-append">
                          <button class="file-upload-browse btn btn-gradient-primary" type="button">选择图片</button>
                        </span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="remark">历程</label>
                            <textarea class="form-control" name="remark" id="remark" rows="4" praceholder="请输入历程">{{$page->remark}}</textarea>
                        </div>
                        <button type="submit" class="btn btn-gradient-primary mr-2">保存</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

code/resources/views/admin/page/editzx.blade.php
@extends('admin.default');
@section("title","招贤纳士")
@section("content")
    <div class="page-header">
        <h3 class="page-title">
            招贤纳士
        </h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">招贤纳士</a></li>
                <li class="breadcrumb-item active" aria-current="page">添加职位</li>
            </ol>
        </nav>
    </div>
    <div class="row">
        <div class="col-md-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    @if ($errors->any())
                        @foreach ($errors->all() as $error)
                        <div class="alert alert-danger">
                            {{ $error }}
                        </div>
                        @endforeach
                    @endif
                    <form class="forms-sample" action="{{route('admin.page.update',['id'=>$page->id])}}" method="post" enctype="multipart/form-data">
                        @csrf
                        @method("PUT")
                        <input type="hidden" name="type" value="2">
                        <div class="form-group">
                            <label for="title">标题</label>
                            <input type="text" name="title" value="{{$page->title}}" class="form-control" id="title" placeholder="请输入标题">
                        </div>
                        <div class="form-group">
                            <label for="contents">职位描述</label>
                            {{--<textarea class="form-control" name="contents" id="contents" rows="4" praceholder="请输入新闻内容"></textarea>--}}
                            <script id="contents" name="contents" type="text/plain">{!! $page->content !!}</script>
                        </div>
                        <button type="submit" class="btn btn-gradient-primary mr-2">保存</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript" id="ne1" charset="utf-8" src="{{ asset(__ADMIN__) }}/neditor/neditor.config.js?v={{time()}}"></script>
    <script type="text/javascript" id="ne2"  charset="utf-8" src="{{ asset(__ADMIN__) }}/neditor/neditor.all.min.js?v={{time()}}"> </script>
    <script type="text/javascript" id="ne3" charset="utf-8" src="{{ asset(__ADMIN__) }}/neditor/neditor.service.js?v={{time()}}"></script>
    <script>
        setTimeout(function(){
            var ue = UE.getEditor('contents', {
                autoHeight: false,
                initialFrameHeight:300
            });
        },1000)
    </script>
@endsection

code/resources/views/admin/page/index.blade.php
@extends('admin.default');
@section("title","招贤纳士管理")
@section("content")
    <div class="page-header">
        <h3 class="page-title">
            <a href="{{route('admin.page.createzx')}}" class="btn btn-danger btn-sm">添加职位</a>
        </h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">招贤纳士</a></li>
                <li class="breadcrumb-item active" aria-current="page">招贤纳士列表</li>
            </ol>
        </nav>
    </div>
    <div class="row">
        <div class="col-md-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    @if(session()->has("data"))
                        <div class="alert alert-{{session("data")['class']}}">
                            {{ session('data')['msg'] }}
                        </div>
                    @endif
                        <form action={} method="POST" id="myform">
                            @csrf
                            @method("DELETE")
                        </form>
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <th class="text-center">ID</th>
                                <th>职位</th>
                                <th class="text-center">发布时间</th>
                                <th class="text-center" style="width:150px;">操作</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($list as $item)
                            <tr>
                                <td class="text-center">{{ $item->id }}</td>
                                <td>{{ $item->title }}</td>
                                <td class="text-center">{{ $item->created_at }}</td>
                                <td class="text-center">
                                    <a class="btn btn-success btn-xs" href="{{ route('admin.page.edit',['page'=>$item->id]) }}" role="button">编辑</a>
                                    <a class="btn btn-danger btn-xs" onclick="dosubmit({{$item->id}})" role="button">删除</a>
                                </td>
                            </tr>
                                @endforeach
                            </tbody>
                        </table>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        function dosubmit(id){
            var src="/admin/page/"+id;
            document.getElementById("myform").action = src;
            document.getElementById("myform").submit();
        }
    </script>
@endsection

code/resources/views/admin/page/licheng.blade.php
@extends('admin.default');
@section("title","发展历程管理")
@section("content")
    <div class="page-header">
        <h3 class="page-title">
            <a href="{{route('admin.page.createlc')}}" class="btn btn-danger btn-sm">添加历程</a>
        </h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">发展历程</a></li>
                <li class="breadcrumb-item active" aria-current="page">发展历程列表</li>
            </ol>
        </nav>
    </div>
    <div class="row">
        <div class="col-md-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    @if(session()->has("data"))
                        <div class="alert alert-{{session("data")['class']}}">
                            {{ session('data')['msg'] }}
                        </div>
                    @endif
                        <form action={} method="POST" id="myform">
                            @csrf
                            @method("DELETE")
                        </form>
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <th class="text-center">ID</th>
                                <th>时间</th>
                                <th class="text-center">发布时间</th>
                                <th class="text-center" style="width:150px;">操作</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($list as $item)
                            <tr>
                                <td class="text-center">{{ $item->id }}</td>
                                <td>{{ $item->title }}</td>
                                <td class="text-center">{{ $item->created_at }}</td>
                                <td class="text-center">
                                    <a class="btn btn-success btn-xs" href="{{ route('admin.page.editlc',['page'=>$item->id]) }}" role="button">编辑</a>
                                    <a class="btn btn-danger btn-xs" onclick="dosubmit({{$item->id}})" role="button">删除</a>
                                </td>
                            </tr>
                                @endforeach
                            </tbody>
                        </table>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        function dosubmit(id){
            var src="/admin/page/"+id;
            document.getElementById("myform").action = src;
            document.getElementById("myform").submit();
        }
    </script>
@endsection