code/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Http\Request;

Route::name("index.")->middleware('spider')->group(function() {
    Route::get('/','Home\IndexController@index')->name("home");
    Route::get('/product','Home\ProductController@index')->name("product.list");
    Route::get('/productshow/{product}','Home\ProductController@show')->name("product.show");
    Route::get('/news','Home\NewsController@index')->name("news.list");
    Route::get('/news/{news}','Home\NewsController@show')->name("news.show");
    Route::get('/cases','Home\CasesController@index')->name("cases.list");
    Route::get('/abount','Home\PageController@index')->name("page.index");
});
//后台路由
Route::prefix("admin")->name("admin.")->middleware('auth')->group(function(){
    Route::get("/","Admin\IndexController@index")->name("home");
    Route::get("/index","Admin\IndexController@index")->name("home");
    Route::group(['prefix'=>'config'],function(){
        Route::get("/site","Admin\ConfigController@siteconfig")->name("config.siteconfig");
        Route::get("/information","Admin\ConfigController@information")->name("config.information");
        Route::get("/baidu","Admin\ConfigController@baidu")->name("config.baidu");
        Route::post("/store","Admin\ConfigController@store")->name("config.store");
    });
    //新闻
    Route::resource("/news","Admin\NewsController")->except(['destroy','create']);
    Route::get('admin/news/add','Admin\NewsController@create')->name('news.create');
    Route::get('admin/news/{news}/del','Admin\NewsController@destroy')->name("news.delete");
    Route::get('admin/news/baidusend/{news}','Admin\NewsController@baidusend')->name("news.baidusend");

    //产品分类
    Route::group(['prefix'=>'category'],function(){
        Route::get("/","Admin\CategoryController@index")->name("category.list");
        Route::match(['get','post'],"/create","Admin\CategoryController@create")->name("category.create");
        Route::match(['get','post'],"/edit/{category}","Admin\CategoryController@edit")->name("category.edit");
        Route::get("/delete/{cate}","Admin\CategoryController@destory")->name("category.delete");
    });
    Route::resource("/product","Admin\ProductController");
    Route::resource("/cases","Admin\CaseController");
    Route::get("/page/createzx","Admin\PageController@createzx")->name('page.createzx');
    Route::get("/page/licheng","Admin\PageController@licheng")->name('page.licheng');
    Route::get("/page/createlc","Admin\PageController@createlc")->name('page.createlc');
    Route::get("/page/editlc/{page}","Admin\PageController@editlc")->name('page.editlc');
    Route::get("/page/jianjie","Admin\PageController@create")->name('page.create');
    Route::resource("/page","Admin\PageController")->except("create");
    Route::resource("/banner","Admin\BannerController");
    Route::post('/banneritem/setsort',"Admin\BanneritemController@setsort")->name('banneritem.setsort');
    Route::resource("/banneritem","Admin\BanneritemController");
    Route::resource("/friend","Admin\FriendController");
    //登录
    Route::get('/logout','Admin\LoginController@logout')->name('login.logout');
    //图片上传
    Route::post('upload','Admin\IndexController@imgupload')->name("upload");
});
Route::get('/admin/login','Admin\LoginController@login')->name('admin.login.login');
Route::post('/admin/dologin','Admin\LoginController@dologin')->name('admin.login.dologin');

code/app/Http/Controllers/Admin/ConfigController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;

class ConfigController extends Controller
{
    // 站点配置界面
    public function siteconfig(){
        $config = $this->getConfig("siteconfig");
        return view("admin.config.siteconfig")->with('config',$config);
    }

    // 基本信息配置界面
    public function information(){
        $config = $this->getConfig("information");
        return view("admin.config.information")->with('config',$config);
    }

    // 百度推送配置界面
    public function baidu(){
        $config = $this->getConfig("baidu");
        return view("admin.config.baidu")->with('config',$config);
    }

    //数据入库
    public function store(Request $request){
        $this->checkdata($request->name,$request);
        $data = $request->only('name','title');
        $conifg = json_encode($request->except('name','title','_token'));
        $data['config']=$conifg;
        $data['created_at']=date("Y/m/d H:i:s",time());
        $data['updated_at']=date("Y/m/d H:i:s",time());
        $config = DB::table("config")->where('name','=',$request->name)->first();
        if($config){
            $result = DB::table('config')->where('name','=',$request->name)->update($data);
        }else{
            $result = DB::table('config')->insert($data);
        }
        if($result===true || $result>0){
            session()->flash("data",['class'=>'success','msg'=>"更新成功"]);
        }else{
            session()->flash("data",['class'=>'danger','msg'=>"更新失败"]);
        }
        return redirect(route('admin.config.'.$request->name));
    }

    private function checkdata($name ="siteconfig",$request){
        switch ($name){
            case "information":
                $datavalidate = $request->validate([
                    'company' =>'required',
                    'address'=>'required',
                    'phone'=>'required'
                ],[
                    'company.required'=>"公司名称不能为空",
                    'address.required'=>"公司地址不能为空",
                    'phone.required'=>'客服热线不能为空',
                ]);
                break;
            case "baidu":
                $datavalidate = $request->validate([
                    'key' =>'required'
                ],[
                    'key.required'=>"密钥不能为空"
                ]);
                break;
            default:
                $datavalidate = $request->validate([
                    'name' =>'required',
                    'title'=>'required',
                    'sitetitle'=>'required',
                    'domain'=>'required|url'
                ],[
                    'name.required'=>"配置标识不能为空",
                    'title.required'=>"配置名称不能为空",
                    'sitetitle.required'=>'网站名称不能为空',
                    'domain.required'=>'网站域名不能为空',
                    'domain.url'=>'网址输入不正确',
                ]);
                break;
        }
    }
//    根据配置标识获取配置信息
    private function getConfig($name = "siteconfig"){
        $res_config = DB::table("config")->where('name','=',$name)->first();
        $config=[];
        if($res_config){
            $config = json_decode($res_config->config,true);
        }
        return $config;
    }
}

code/resources/views/admin/config/baidu.blade.php
@extends('admin.default');
@section("title","系统配置")
@section("content")
    <div class="page-header">
        <h3 class="page-title">
            系统配置
        </h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">系统配置</a></li>
                <li class="breadcrumb-item active" aria-current="page">百度推送</li>
            </ol>
        </nav>
    </div>
    <div class="row">
        <div class="col-md-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    @if ($errors->any())
                        @foreach ($errors->all() as $error)
                        <div class="alert alert-danger">
                            {{ $error }}
                        </div>
                        @endforeach
                    @endif
                    @if(session()->has("data"))
                            <div class="alert alert-{{session("data")['class']}}">
                                {{ session('data')['msg'] }}
                            </div>
                     @endif

                    <form class="forms-sample" action="{{route('admin.config.store')}}" method="post">
                        @csrf
                        <input type="hidden" name="name" value="baidu">
                        <input type="hidden" name="title" value="百度推送">
                        <div class="form-group">
                            <label for="domain">域名</label>
                            <input type="text" value="{{isset($config['domain'])?$config['domain']:''}}" name="domain" class="form-control" id="domain" placeholder="请输入域名">
                        </div>
                        <div class="form-group">
                            <label for="checkkey">百度验证</label>
                            <input type="text" value="{{isset($config['checkkey'])?$config['checkkey']:''}}" name="checkkey" class="form-control" id="checkkey" placeholder="请输入百度验证">
                        </div>
                        <div class="form-group">
                            <label for="key">百度密钥</label>
                            <input type="text" value="{{isset($config['key'])?$config['key']:''}}" name="key" class="form-control" id="key" placeholder="请输入百度密钥">
                        </div>
                        <button type="submit" class="btn btn-gradient-primary mr-2">保存</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

code/resources/views/admin/config/information.blade.php
@extends('admin.default');
@section("title","系统配置")
@section("content")
    <div class="page-header">
        <h3 class="page-title">
            系统配置
        </h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">系统配置</a></li>
                <li class="breadcrumb-item active" aria-current="page">基本信息配置</li>
            </ol>
        </nav>
    </div>
    <div class="row">
        <div class="col-md-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    @if ($errors->any())
                        @foreach ($errors->all() as $error)
                        <div class="alert alert-danger">
                            {{ $error }}
                        </div>
                        @endforeach
                    @endif
                    @if(session()->has("data"))
                            <div class="alert alert-{{session("data")['class']}}">
                                {{ session('data')['msg'] }}
                            </div>
                     @endif

                    <form class="forms-sample" action="{{route('admin.config.store')}}" method="post">
                        @csrf
                        <input type="hidden" name="name" value="information">
                        <input type="hidden" name="title" value="基本信息配置">
                        <div class="form-group">
                            <label for="company">公司名称</label>
                            <input type="text" value="{{isset($config['company'])?$config['company']:''}}" name="company" class="form-control" id="company" placeholder="请输入公司名称">
                        </div>
                        <div class="form-group">
                            <label for="address">地址</label>
                            <input type="text" name="address" value="{{isset($config['address'])?$config['address']:''}}" class="form-control" id="address" placeholder="请输入公司地址">
                        </div>
                        <div class="form-group">
                            <label for="phone">客服热线</label>
                            <input type="text" name="phone" value="{{isset($config['phone'])?$config['phone']:''}}" class="form-control" id="phone" placeholder="请输入客服热线">
                        </div>
                        <div class="form-group">
                            <label for="email">邮箱</label>
                            <input type="text" name="email" value="{{isset($config['email'])?$config['email']:''}}" class="form-control" id="email" placeholder="请输入邮箱">
                        </div>
                        <div class="form-group">
                            <label for="copyright">备案号</label>
                            <input type="text" name="copyright" value="{{isset($config['copyright'])?$config['copyright']:''}}" class="form-control" id="phone" placeholder="请输入备案号">
                        </div>
                        <button type="submit" class="btn btn-gradient-primary mr-2">保存</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

code/resources/views/admin/config/siteconfig.blade.php
@extends('admin.default');
@section("title","系统配置")
@section("content")
    <div class="page-header">
        <h3 class="page-title">
            系统配置
        </h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">系统配置</a></li>
                <li class="breadcrumb-item active" aria-current="page">网站配置</li>
            </ol>
        </nav>
    </div>
    <div class="row">
        <div class="col-md-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    @if ($errors->any())
                        @foreach ($errors->all() as $error)
                        <div class="alert alert-danger">
                            {{ $error }}
                        </div>
                        @endforeach
                    @endif
                    @if(session()->has("data"))
                            <div class="alert alert-{{session("data")['class']}}">
                                {{ session('data')['msg'] }}
                            </div>
                     @endif

                    <form class="forms-sample" action="{{route('admin.config.store')}}" method="post">
                        @csrf
                        <input type="hidden" name="name" value="siteconfig">
                        <input type="hidden" name="title" value="网站配置">
                        <div class="form-group">
                            <label for="sitetitle">网站名称</label>
                            <input type="text" value="{{isset($config['sitetitle'])?$config['sitetitle']:''}}" name="sitetitle" class="form-control" id="sitetitle" placeholder="请输入网站名称">
                        </div>
                        <div class="form-group">
                            <label for="domain">网站域名</label>
                            <input type="text" name="domain" value="{{isset($config['domain'])?$config['domain']:''}}" class="form-control" id="domain" placeholder="请输入网站域名">
                        </div>
                        <div class="form-group">
                            <label for="keyword">网站关键字</label>
                            <input type="text" name="keyword" value="{{isset($config['keyword'])?$config['keyword']:''}}" class="form-control" id="keyword" placeholder="请输入网站关键字">
                        </div>
                        <div class="form-group">
                            <label for="desc">网站描述</label>
                            <textarea class="form-control" name="desc" id="desc" rows="4" placeholder="请输入网站描述">{{isset($config['desc'])?$config['desc']:''}}</textarea>
                        </div>
                        <div class="form-group">
                            <label class="col-form-label">网站状态</label>
                            <div class="row">
                                <div class="col-sm-4 col-md-2 col-lg-1">
                                    <div class="form-check">
                                        <label class="form-check-label">
                                            @if(isset($config['status']))
                                                <input type="radio" class="form-check-input" name="status" id="status" value="1" {{($config['status']==1)?'checked':''}}>
                                            @else
                                                <input type="radio" class="form-check-input" name="status" id="status" value="1" checked>
                                            @endif
                                                运行
                                            <i class="input-helper"></i></label>
                                    </div>
                                </div>
                                <div class="col-sm-4 col-md-2 col-lg-1">
                                    <div class="form-check">
                                        <label class="form-check-label">
                                            @if(isset($config['status']))
                                            <input type="radio" class="form-check-input" name="status" id="status" value="0" {{($config['status']==0)?'checked':''}}>
                                            @else
                                                <input type="radio" class="form-check-input" name="status" id="status" value="0">
                                            @endif
                                                停止
                                            <i class="input-helper"></i></label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="closeinfo">关站提示</label>
                            <textarea class="form-control" name="closeinfo" id="desc" rows="4" praceholder="请输入关站提示信息">{{isset($config['closeinfo'])?$config['closeinfo']:''}}</textarea>
                        </div>
                        <button type="submit" class="btn btn-gradient-primary mr-2">保存</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection