code/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Http\Request;

Route::name("index.")->middleware('spider')->group(function() {
    Route::get('/','Home\IndexController@index')->name("home");
    Route::get('/product','Home\ProductController@index')->name("product.list");
    Route::get('/productshow/{product}','Home\ProductController@show')->name("product.show");
    Route::get('/news','Home\NewsController@index')->name("news.list");
    Route::get('/news/{news}','Home\NewsController@show')->name("news.show");
    Route::get('/cases','Home\CasesController@index')->name("cases.list");
    Route::get('/abount','Home\PageController@index')->name("page.index");
});
//后台路由
Route::prefix("admin")->name("admin.")->middleware('auth')->group(function(){
    Route::get("/","Admin\IndexController@index")->name("home");
    Route::get("/index","Admin\IndexController@index")->name("home");
    Route::group(['prefix'=>'config'],function(){
        Route::get("/site","Admin\ConfigController@siteconfig")->name("config.siteconfig");
        Route::get("/information","Admin\ConfigController@information")->name("config.information");
        Route::get("/baidu","Admin\ConfigController@baidu")->name("config.baidu");
        Route::post("/store","Admin\ConfigController@store")->name("config.store");
    });
    //新闻
    Route::resource("/news","Admin\NewsController")->except(['destroy','create']);
    Route::get('admin/news/add','Admin\NewsController@create')->name('news.create');
    Route::get('admin/news/{news}/del','Admin\NewsController@destroy')->name("news.delete");
    Route::get('admin/news/baidusend/{news}','Admin\NewsController@baidusend')->name("news.baidusend");

    //产品分类
    Route::group(['prefix'=>'category'],function(){
        Route::get("/","Admin\CategoryController@index")->name("category.list");
        Route::match(['get','post'],"/create","Admin\CategoryController@create")->name("category.create");
        Route::match(['get','post'],"/edit/{category}","Admin\CategoryController@edit")->name("category.edit");
        Route::get("/delete/{cate}","Admin\CategoryController@destory")->name("category.delete");
    });
    Route::resource("/product","Admin\ProductController");
    Route::resource("/cases","Admin\CaseController");
    Route::get("/page/createzx","Admin\PageController@createzx")->name('page.createzx');
    Route::get("/page/licheng","Admin\PageController@licheng")->name('page.licheng');
    Route::get("/page/createlc","Admin\PageController@createlc")->name('page.createlc');
    Route::get("/page/editlc/{page}","Admin\PageController@editlc")->name('page.editlc');
    Route::get("/page/jianjie","Admin\PageController@create")->name('page.create');
    Route::resource("/page","Admin\PageController")->except("create");
    Route::resource("/banner","Admin\BannerController");
    Route::post('/banneritem/setsort',"Admin\BanneritemController@setsort")->name('banneritem.setsort');
    Route::resource("/banneritem","Admin\BanneritemController");
    Route::resource("/friend","Admin\FriendController");
    //登录
    Route::get('/logout','Admin\LoginController@logout')->name('login.logout');
    //图片上传
    Route::post('upload','Admin\IndexController@imgupload')->name("upload");
});
Route::get('/admin/login','Admin\LoginController@login')->name('admin.login.login');
Route::post('/admin/dologin','Admin\LoginController@dologin')->name('admin.login.dologin');

code/app/Cases.php
<?php

namespace App;

use App\Events\CasesDeleteEvent;
use Illuminate\Database\Eloquent\Model;

class Cases extends Model
{
    protected $dispatchesEvents =[
        'deleted'=> CasesDeleteEvent::class,
    ];
}

code/app/Http/Controllers/Admin/CaseController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Cases;
use App\Http\Requests\StoreCasesPost;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;

class CaseController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //获取案例列表数据
        $list = Cases::OrderBy('sort',"Desc")->OrderBy('id',"Desc")->paginate(10);
        return view("admin.case.index")->with('list',$list);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        //加载视图
        return view("admin.case.create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreCasesPost $request)
    {
        $CasesModel = new Cases;
        $CasesModel->title = $request->title;
        $CasesModel->remark = $request->remark;
        $CasesModel->sort = $request->sort;
        if($request->file("file")){
            $CasesModel->pic = $request->file('file')->store('cases');
        }
        checkreturn($CasesModel->save(),"新增");
        return redirect(route('admin.cases.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Cases $case)
    {
        return view('admin.case.edit')->with('cases',$case);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreCasesPost $request, $id)
    {

        $CasesModel = Cases::find($id);
        $CasesModel->title = $request->title;
        $CasesModel->remark = $request->remark;
        $CasesModel->sort = $request->sort;
        if($request->file("file")){
            $CasesModel->pic = $request->file('file')->store('cases');
            //删除旧图片
            Storage::delete($request->pic);
        }
        checkreturn($CasesModel->save(),"编辑");
        return redirect(route('admin.cases.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request,$id)
    {
        $ids =[];
        if($id!=0){
            $ids[]=$id;
        }else{
            if($request->has('ids')){
                $ids = $request->ids;
            }
        }
        $counts = Cases::destroy($ids);
        checkreturn($counts>0,"删除");
        return redirect(route('admin.cases.index'));
    }
}

code/resources/views/admin/case/create.blade.php
@extends('admin.default');
@section("title","案例管理")
@section("content")
    <div class="page-header">
        <h3 class="page-title">
            案例管理
        </h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">案例管理</a></li>
                <li class="breadcrumb-item active" aria-current="page">添加案例</li>
            </ol>
        </nav>
    </div>
    <div class="row">
        <div class="col-md-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    @if ($errors->any())
                        @foreach ($errors->all() as $error)
                        <div class="alert alert-danger">
                            {{ $error }}
                        </div>
                        @endforeach
                    @endif
                    <form class="forms-sample" action="{{route('admin.cases.store')}}" method="post" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group">
                            <label for="title">案例标题</label>
                            <input type="text" name="title" class="form-control" id="title" placeholder="请输入标题">
                        </div>

                        <div class="form-group">
                            <label for="remark">摘要</label>
                            <textarea class="form-control" name="remark" id="remark" rows="4" placeholder="请输入摘要"></textarea>
                        </div>

                        <div class="form-group">
                            <label>图片上传</label>
                            <input type="file" name="file" class="file-upload-default">
                            <div class="input-group col-xs-12">
                                <input type="text" class="form-control file-upload-info" disabled="" placeholder="图片上传">
                                <span class="input-group-append">
                          <button class="file-upload-browse btn btn-gradient-primary" type="button">选择图片</button>
                        </span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="sort">排序</label>
                            <input type="text" name="sort" value="100" class="form-control" id="sort">
                        </div>
                        <button type="submit" class="btn btn-gradient-primary mr-2">保存</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

code/resources/views/admin/case/edit.blade.php
@extends('admin.default');
@section("title","案例管理")
@section("content")
    <div class="page-header">
        <h3 class="page-title">
            案例管理
        </h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">案例管理</a></li>
                <li class="breadcrumb-item active" aria-current="page">编辑案例</li>
            </ol>
        </nav>
    </div>
    <div class="row">
        <div class="col-md-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    @if ($errors->any())
                        @foreach ($errors->all() as $error)
                        <div class="alert alert-danger">
                            {{ $error }}
                        </div>
                        @endforeach
                    @endif
                    <form class="forms-sample" action="{{route('admin.cases.update',['cases'=>$cases->id])}}" method="post" enctype="multipart/form-data">
                        @csrf
                        @method("PUT")
                        <div class="form-group">
                            <label for="title">案例标题</label>
                            <input type="text" name="title" value="{{$cases->title}}" class="form-control" id="title" placeholder="请输入标题">
                        </div>

                        <div class="form-group">
                            <label for="remark">摘要</label>
                            <textarea class="form-control" name="remark" id="remark" rows="4" placeholder="请输入摘要">{{$cases->remark}}</textarea>
                        </div>

                        <div class="form-group">
                            <label>图片上传</label>
                            <input type="file" name="file" class="file-upload-default">
                            <div class="input-group col-xs-12">
                                <input type="text" value="{{$cases->pic}}" class="form-control file-upload-info" disabled="" placeholder="图片上传">
                                <span class="input-group-append">
                          <button class="file-upload-browse btn btn-gradient-primary" type="button">选择图片</button>
                        </span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="sort">排序</label>
                            <input type="text" value="{{$cases->sort}}" name="sort" value="100" class="form-control" id="sort">
                        </div>
                        <button type="submit" class="btn btn-gradient-primary mr-2">保存</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

code/resources/views/admin/case/index.blade.php
@extends('admin.default');
@section("title","案例管理")
@section("content")
    <div class="page-header">
        <h3 class="page-title">
            <a href="{{route('admin.cases.create')}}" class="btn btn-success btn-xs">添加案例</a>
        </h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">案例管理</a></li>
                <li class="breadcrumb-item active" aria-current="page">案例列表</li>
            </ol>
        </nav>
    </div>
    <div class="row">
        <div class="col-md-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    @if(session()->has("data"))
                        <div class="alert alert-{{session("data")['class']}}">
                            {{ session('data')['msg'] }}
                        </div>
                    @endif
                    <form action={} method="POST" id="myform">
                        @csrf
                        @method("DELETE")
                    </form>
                    <div class="table-responsive">
                        <form action="{{route('admin.cases.destroy',['id'=>0])}}" method="post">
                            @csrf
                            @method("DELETE ")
                            <input type="submit" value="批量删除" class="btn btn-danger btn-lg">
                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <th style="width:45px;">
                                    <div class="form-check form-check-danger">
                                        <label class="form-check-label">
                                            <input class="form-check-input" type="checkbox" id="ischecked">
                                        </label>
                                    </div>
                                </th>
                                <th class="text-center" style="width: 60px;">ID</th>
                                <th>名称</th>
                                <th class="text-center" style="width:165px;">发布时间</th>
                                <th class="text-center" style="width:150px;">操作</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($list as $item)
                            <tr>
                                <td class="text-center">
                                    <div class="form-check form-check-danger">
                                        <label class="form-check-label">
                                            <input class="form-check-input mychecked" name="ids[]" value="{{ $item->id }}" type="checkbox">
                                        </label>
                                    </div>
                                </td>
                                <td class="text-center">{{ $item->id }}</td>
                                <td>{{ $item->title }}</td>
                                <td class="text-center">{{ $item->created_at }}</td>
                                <td class="text-center">
                                    <a class="btn btn-success btn-xs" href="{{ route('admin.cases.edit',['case'=>$item->id]) }}" role="button">编辑</a>
                                    <a class="btn btn-danger btn-xs" href="javascript:;" onclick="dosubmit({{$item->id}})" role="button">删除</a>
                                </td>
                            </tr>
                                @endforeach
                            </tbody>
                        </table>
                        </form>
                        <div style="padding:10px 0;">
                            {{ $list->links() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="{{ asset(__ADMIN__) }}/js/misc.js?v={{time()}}"></script>
    <script>
        function dosubmit(id){
            var src="/admin/cases/"+id;
            document.getElementById("myform").action = src;
            document.getElementById("myform").submit();
        }
    </script>
@endsection